import { chromium } from "@playwright/test";
import { mkdirSync } from "node:fs";
import assert from "node:assert/strict";
mkdirSync("artifacts", { recursive: true });
const browser = await chromium.launch({ channel: "msedge", headless: true, args: ["--disable-gpu"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const base = process.env.STOREFRONT_URL || "http://localhost:3000";
try {
  await page.goto(base, { waitUntil: "networkidle", timeout: 120000 });
  await page.locator(".hero img").waitFor();
  await page.screenshot({ path: "artifacts/home-desktop.png", fullPage: true });
  assert.equal(await page.locator("h1").count(), 1);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, "Desktop overflow");
  const heroLoaded = await page.locator(".hero img").evaluate(img => img.complete && img.naturalWidth > 0);
  assert.equal(heroLoaded, true, "Hero image failed");
  await page.getByRole("button", { name: "Search jewellery", exact: true }).click();
  await page.getByRole("textbox", { name: "Search jewellery", exact: true }).fill("pearl");
  await page.locator(".search-result").first().waitFor();
  assert.match(await page.locator(".search-result").first().innerText(), /Pearl/);
  await page.keyboard.press("Escape");
  const first = page.locator(".product-card").first();
  await first.getByRole("button", { name: /Save .* to wishlist/ }).click();
  await first.getByRole("button", { name: "Add to bag", exact: true }).click();
  await page.getByRole("button", { name: /Open shopping bag/ }).click();
  await page.locator(".bag-item").waitFor();
  await page.getByRole("button", { name: /Increase .* quantity/ }).click();
  assert.equal(await page.locator(".quantity span").innerText(), "2");
  await page.getByRole("textbox", { name: "Offer code" }).fill("WELCOME10");
  await page.getByRole("button", { name: "Apply", exact: true }).click();
  await page.getByText("WELCOME10 applied").waitFor();
  await page.screenshot({ path: "artifacts/cart-desktop.png" });
  await page.keyboard.press("Escape");
  await page.reload({ waitUntil: "networkidle" });
  assert.match(await page.getByRole("button", { name: /Open shopping bag/ }).getAttribute("aria-label"), /2 items/);
  await page.getByRole("button", { name: "Switch to dark mode" }).click();
  assert.equal(await page.locator("html").getAttribute("data-theme"), "dark");
  await page.screenshot({ path: "artifacts/home-dark.png" });
  await page.getByRole("button", { name: "Switch to light mode" }).click();
  await page.goto(base + "/collections/all", { waitUntil: "networkidle" });
  await page.getByRole("combobox", { name: "Sort products" }).selectOption("low");
  assert.match(await page.locator(".product-card h3").first().innerText(), /Kundan Statement Ring/);
  await page.getByRole("checkbox", { name: "925 sterling silver", exact: true }).check();
  assert.equal(await page.locator(".product-card").count(), 1);
  await page.goto(base + "/products/emerald-drop-earrings", { waitUntil: "networkidle" });
  await page.getByRole("button", { name: "Zoom in", exact: true }).click();
  assert.equal(await page.locator(".zoomed").count(), 1);
  await page.getByRole("textbox", { name: "Delivery to your door" }).fill("12");
  await page.getByRole("button", { name: "Check", exact: true }).click();
  await page.getByText("Please enter a valid 6-digit Indian pincode.").waitFor();
  await page.screenshot({ path: "artifacts/product-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base, { waitUntil: "networkidle" });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, "Mobile overflow");
  await page.locator(".hero img").evaluate(img => img.decode());
  await page.screenshot({ path: "artifacts/home-mobile-viewport.png" });
  await page.screenshot({ path: "artifacts/home-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Open menu", exact: true }).click();
  await page.getByRole("dialog").getByRole("link", { name: "Earrings", exact: true }).click();
  await page.getByRole("button", { name: "Filter", exact: true }).click();
  await page.getByRole("checkbox", { name: "In stock only", exact: true }).check();
  await page.getByRole("button", { name: /Show .* pieces/ }).click();
  assert.equal(await page.getByRole("dialog").count(), 0);
  await page.screenshot({ path: "artifacts/collection-mobile.png", fullPage: true });
  await page.goto(base + "/products/bridal-kundan-necklace", { waitUntil: "networkidle" });
  assert.equal(await page.getByRole("button", { name: "Out of stock", exact: true }).first().isDisabled(), true);
  await page.goto(base + "/checkout", { waitUntil: "networkidle" });
  await page.getByRole("button", { name: "Review details", exact: true }).click();
  await page.getByText("Enter your full name.").waitFor();
  await page.goto(base + "/wishlist", { waitUntil: "networkidle" });
  assert.equal(await page.locator(".product-card").count(), 1);
  await page.goto(base + "/search?q=does-not-exist", { waitUntil: "networkidle" });
  assert.equal(await page.locator(".product-card").count(), 0);
  for (const width of [320, 768, 1024, 1920]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(base, { waitUntil: "networkidle" });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, "Overflow at " + width);
  }
  assert.deepEqual(errors, [], "Browser runtime errors");
  console.log("PASS: responsive layouts, images, search, wishlist, persistent bag, coupon, theme, filters, sorting, product zoom, pincode validation, mobile menu.");
} finally { await browser.close(); }
